#include <QMainWindow>
#include <QQmlEngine>
#include <QQmlComponent>
#include <QQuickView>
#include <QQuickItem>
#include <QQuickWidget>
#include <QQmlProperty>
#include <QSettings>
#include <QMetaEnum>
#include <QQmlContext>
#include <QQmlApplicationEngine>
#include <QTimer>
#include <QApplication>
#include <QDateTime>
#include <QThread>
#include <QMutex>
#include <QRunnable>

#include "Globals.h"
