#include <QMainWindow>
#include <QQmlEngine>
#include <QQmlComponent>
#include <QQuickView>
#include <QQuickItem>
#include <QQuickWidget>
#include <QQmlProperty>
#include <QSettings>
#include <QMetaEnum>
#include "Globals.h"
